base_url = "https://nice-island-07bfc7a0f.7.azurestaticapps.net"
title = "Caleb Dudley"
description = "Caleb Dudley — Software Engineer focused on DevOps, Cloud Architecture, Python, Linux, and IoT."
compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]
