base_url = "https://calebdudley.dev"
title = "Caleb Dudley"
description = "Caleb Dudley — Software Engineer focused on DevOps, .NET, Python, Linux, and IoT."
compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]
